<?php
// TODO: Check for accessibility (WCAG / ARIA)
// AK: Add JavaScript translations for use in popover
$this->jsTranslations()->addStrings(
        [
            'currentTerm' => 'currentTerm',
            'currentAndPreviousTerms' => 'currentAndPreviousTerms',
            'searchFor' => 'Search For'
        ]
);


$keywordSeparator = ' <i class="fa fa-minus akKeywordChainSeparator" aria-hidden="true"></i> ';
?>

<!-- Include Bootstrap 5 CSS and JS (the bundle includes Popper) -->

<script>
    // Wait until the DOM is fully loaded
    $(document).ready(function () {
        // Select all elements with data-bs-toggle="popover"
        var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'));

        // Initialize each popover
        var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
            console.log(popoverTriggerEl);
            return new bootstrap.Popover(popoverTriggerEl, {
                html: true,
                //content: 'eeeee'
            });
        });
    });
</script>

<?php foreach ($data as $keywords): ?>

    <div class="subject-line" property="keywords">
        <?php
        // AK: Create some variables
        $keywordChain = '';
        $keywordChainSeparated = '';
        ?>
        <?php if (count($keywords) == 1) $keywords = explode('--', $keywords[0]); ?>
        <?php
        $i = 0;
        foreach ($keywords as $keyword):
            ?>
            <?php // AK: Add a "minus" character from font-awesome to separate the single keywords in a keyword chain from each other. ?>
            <?= ($i == 0) ? '' : $keywordSeparator ?>
            <?php
            // AK: Create non-separated keyword chain. The individual keywords are surounded by double-quotes: this is important if the keyword contains spaces.
            $keywordChain = trim($keywordChain) . ' "' . trim($keyword) . '"';
            // AK: $keywordChainSeparated is passed to popover JavaScript for showing a nice separated keyword chain
            $keywordChainSeparated = trim($keywordChainSeparated) . (($i == 0) ? '' : $keywordSeparator) . trim($this->escapeHtml($keyword));
            ?>

            <?php if ($i == 0) : ?>
                <?php /* AK: The first element of the keyword chain gets a "normal" link as a popover would not make sense (there are no previous keywords if the first one is chosen) */ ?>
                <a title="<?= $this->escapeHtmlAttr($keywordChain) ?>" href="<?= $this->record($this->driver)->getLink('subject', $keywordChain) ?>" rel="nofollow"><?= trim($this->escapeHtml($keyword)) ?></a>
            <?php else: ?>
                <?php /* AK: A click on a keyword (except the first one - see above) in the keyword chain opens a popup where the user can choose if he wants to search only for the current term or for the current term AND all previous terms. */ ?>

                <?php
                $pkeyword = trim($this->escapeHtmlAttr($this->escapeHtml($keyword)));
                $pKeywordLink = $this->escapeHtmlAttr($this->record($this->driver)->getLink('subject', '"' . $keyword . '"'));
                $pKeywordchainSeparated = $this->escapeHtmlAttr($keywordChainSeparated);
                $pKeywordchainLink = $this->escapeHtmlAttr($this->record($this->driver)->getLink('subject', $keywordChain));
                $currentTerm = $this->transEsc('currentTerm');
                $content = "<div class='popoverEntry'>" . $currentTerm . ":<br />"
                        . "<a href='" . $pKeywordLink . "'>" . $pkeyword . "</a>"
                        . "</div><div class='popoverEntry'>"
                        . $this->transEsc('currentAndPreviousTerms') . ":<br />"
                        . "<a href='" . $pKeywordchainLink . "'>" . $pKeywordchainSeparated . "</a></div>";
                
                ?>
                <a type="button"
                   class="popover-link"
                   tabindex="0"
                   role="button"
                   data-bs-title="<?= $this->transEsc('searchFor') ?>..."
                   data-bs-trigger="focus"
                   data-bs-placement="bottom" 
                   data-bs-content="<?= $content ?>"
                   data-bs-toggle="popover" 
                   rel="nofollow"
                   ><?= trim($this->escapeHtml($keyword)) ?></a>
               <?php endif; ?>

            <?php
            // AK: Increase the counter so that we know if we are processing the first keyword of the chain or a later one.
            $i++;
            ?>
        <?php endforeach; ?>
    </div>
<?php endforeach; ?>
