<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbf620a9eb1068ab2016173c7f84fbee8
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'ScssPhp\\ScssPhp\\' => 16,
        ),
        'A' => 
        array (
            'AcdhchTheme\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ScssPhp\\ScssPhp\\' => 
        array (
            0 => __DIR__ . '/..' . '/scssphp/scssphp/src',
        ),
        'AcdhchTheme\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/acdhchTheme',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbf620a9eb1068ab2016173c7f84fbee8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbf620a9eb1068ab2016173c7f84fbee8::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbf620a9eb1068ab2016173c7f84fbee8::$classMap;

        }, null, ClassLoader::class);
    }
}
