<?php
try {
    $holdings = $this->driver->getHolding991992();    
    
} catch (\VuFind\Exception\ILS $e) {
    $holdings = [
        'holdings' => [],
        'total' => 0,
        'page' => 0,
        'itemLimit' => 0
    ];
}
//table translated text
$str991 = array(
    "a" => $this->translate("991a"), 
    "b" => $this->translate("991b"),
    "c" => $this->translate("991c"),
    "d" => $this->translate("991d"), 
    "e" => $this->translate("991e"), 
    "f" => $this->translate("991f"),
    "g" => $this->translate("991g"), 
    "h" => $this->translate("991h"),
    "k" => $this->translate("991k"), 
    "l" => $this->translate("991l"),
    "m" => $this->translate("991m"), 
    "p" => $this->translate("991p"), 
    "q" => $this->translate("991q"),
    "r" => $this->translate("991r"), 
    "s" => $this->translate("991s")
);
$str992 = array(
    "a" => $this->translate("992a"),
    "b" => $this->translate("992b"), "c" => $this->translate("992c"),
    "d" => $this->translate("992d"), "e" => $this->translate("992e"),
    "f" => $this->translate("992f"), "g" => $this->translate("992g"), "i" => $this->translate("992i"),
    "j" => $this->translate("992j"), "k" => $this->translate("992k"), "l" => $this->translate("992l"),
    "m" => $this->translate("992m"), "t" => $this->translate("992t")
);

function createRow(string $label, string $text) {    
    ?>
    <tr>
    <td><?=$label?></td>
    <td><?=$text?></td>
    </tr>
    <?php
}

function createTable(array $data, array $labels) {

    echo '<table class="table table-striped">';
        foreach($labels as $k => $v) {
            if(isset($data[$k][0])) {
                createRow($v, $data[$k][0]);
            }
        }
    echo '</table>';
}

?>

<?php if(count($holdings) > 0) :  ?>
    <?php foreach($holdings as $name => $d) : ?>
    <?php 
        if($d['exemplarbeschreibung']) {
            createTable($d['exemplarbeschreibung'], $str992);
        }

        if($d['exLibris']) {
             createTable($d['exLibris'], $str991);
        }
    ?>

    <?php endforeach;?> 

<?php else: ?>
    <div class="alert alert-info">
        <p><?php echo $this->transEsc("No Data"); ?></p>
    </div>
<?php endif; ?>

       
   